apiVersion: 1

datasources:
  - name: MDT Postgres
    uid: mdt-postgres
    type: postgres
    access: proxy
    url: ${MDT_GRAFANA_DB_HOST}
    user: ${MDT_GRAFANA_DB_USER}
    secureJsonData:
      password: ${MDT_GRAFANA_DB_PASSWORD}
    jsonData:
      database: ${MDT_GRAFANA_DB_NAME}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 20
      maxIdleConns: 20
      connMaxLifetime: 14400
      connMaxIdleTime: 14400
